// Code generated by sqlc. DO NOT EDIT.

package db

import ()

type Scrape struct {
	ID        int64       `json:"id"`
	UserID    int32       `json:"userID"`
	Url       string      `json:"url"`
	Scrapped  string      `json:"scrapped"`
	CreatedAt interface{} `json:"createdAt"`
}

type User struct {
	ID        int64       `json:"id"`
	Username  string      `json:"username"`
	Password  string      `json:"password"`
	CreatedAt interface{} `json:"createdAt"`
}
