// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Scrape struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"userID"`
	Url       string    `json:"url"`
	Scrapped  string    `json:"scrapped"`
	CreatedAt time.Time `json:"createdAt"`
}

type User struct {
	ID        int32     `json:"id"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"createdAt"`
}
