// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"time"
)

type Querier interface {
	CountOwnScrape(ctx context.Context, userID int32) (int64, error)
	CountScrape(ctx context.Context) (int64, error)
	CreateScrape(ctx context.Context, arg CreateScrapeParams) (Scrape, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	Filter(ctx context.Context, arg FilterParams) ([]FilterRow, error)
	GetOwnScrape(ctx context.Context, arg GetOwnScrapeParams) ([]GetOwnScrapeRow, error)
	GetScrape(ctx context.Context, id int32) ([]GetScrapeRow, error)
	GetUser(ctx context.Context, username string) (User, error)
	MinDate(ctx context.Context) (time.Time, error)
	Search(ctx context.Context, url string) ([]SearchRow, error)
}

var _ Querier = (*Queries)(nil)
